### ISSUE TITLE
Update UNIVERSAL::TO_JSON to have package markup

### ISSUE THREAD

**Issue by burnersk** [makamaka/JSON#12]
Please update UNIVERSAL::TO_JSON to match the following logic:

    *UNIVERSAL::TO_JSON = sub {
      my ($self)  = @_;
      my $package = ref $self;
      my $b_obj   = B::svref_2object( $_[0] );
      my $type = $b_obj->isa('B::HV') ? 'hash' : $b_obj->isa('B::AV') ? 'array' : '';
      return {
        "!!perl/$type:$package" => (
            $type eq 'hash'  ? { %{$self} }
          : $type eq 'array' ? [ @{$self} ]
          :                    undef
        ),
      };
    };

It is not possible to detect what object is serialized. `YAML` have markup for that, `JSON` don't.

Demo
--------

    package OBJ {
      use Moo qw( :syntax );
      use MooX::Types::MooseLike::Base qw( Str );
      has label => (
        is      => 'rw',
        isa     => Str,
        default => sub { q{} },
      );
    }
  
    package OBJ2 {
      sub new {
        my ( $class, %params ) = @_;
        my $self = bless [''], $class;
        $self->label($params{label}) if exists $params{label};
        return $self;
      }
      sub label {
        my ( $self, @params ) = @_;
        if ( scalar @params ) {
          $self->[0] = $params[0];
        }
        return $self->[0];
      }
    }

Original `TO_JSON`
----------------------------

    use JSON qw( -convert_blessed_universally );
    say JSON->new->allow_blessed->convert_blessed->encode( [
      OBJ->new( label => 'foo' ),
      OBJ2->new( label => 'bar' ),
    ] );
    ## [ { "label": "foo" }, [ "bar" ] ]

New implementation of `TO_JSON`
--------------------------------------------------

    use JSON qw( -convert_blessed_universally );
    say JSON->new->allow_blessed->convert_blessed->encode( [
      OBJ->new( label => 'foo' ),
      OBJ2->new( label => 'bar' ),
    ] );
    ## [ { "!!perl/hash:OBJ": { "label": "foo" } }, { "!!perl/array:OBJ2": [ "bar" ] } ]

Inspired from `YAML`
------------------------------

    use YAML;
    say YAML::Dump(  [
      OBJ->new( label => 'foo' ),
      OBJ2->new( label => 'bar' ),
    ]  );
    ## ---
    ## - !!perl/hash:OBJ
    ##   label: foo
    ## - !!perl/array:OBJ2
    ##   - bar

**Comment by charsbar** [comment]
No, we won't. This breaks backward compatibility significantly.
