### ISSUE TITLE
neither allow_blessed nor convert_blessed settings are enabled

### ISSUE THREAD

**Issue by aduitsis** [makamaka/JSON#15]
I have a class named FactSet which contains an array of objects of class Fact. I tried to implement a method like this for FactSet:

``` perl
sub TO_JSON {
         JSON->new->utf8->allow_blessed->convert_blessed->encode( $_[0]->facts );
 }
```

The items inside $_[0]->facts are blessed objects of class Fact and this class implements a TO_JSON method. However, when I try to call $fact_set->TO_JSON I get 

``` perl
encountered object 'SNMP::Class::Fact=HASH(0x803b9c7b0)', but neither allow_blessed nor convert_blessed settings are enabled at ...
```

Is this normal? Should it not descend into the array and convert each object by using its TO_JSON method ?

**Comment by charsbar** [comment]
I couldn't reproduce this issue. Could you tell me if this still happens to you with the latest versions of JSON/JSON::PP/JSON::XS modules? (please make sure you load the right version of your module, too)
