### ISSUE TITLE
Allow for another false value: \''

### ISSUE THREAD

**Issue by rkleemann** [makamaka/JSON#38]
Currently JSON accepts two scalar references as values, \0 and \1, which mean false and true respectively.  However, Perl returns the empty string as a false value from most functions.  JSON should accept a reference to the empty string as a false value, to stay consistent with Perl.

    $ perl -MJSON -E 'say JSON->new->encode([!!1, \!!1])'
    [1,true]
    $ perl -MJSON -E 'say JSON->new->encode([!!0, \!!0])'
    cannot encode reference to scalar at -e line 1.

To get the latter one to work is less obvious:

    $ perl -MJSON -E 'say JSON->new->encode([!!0, \(0+!!0)])'
    ["",false]

Which means to be consistent, casting any boolean function from perl to a JSON false/true value is excessively verbose:

    $ perl -MJSON -E 'say JSON->new->encode([defined(undef), \(0+defined(undef))])'
    ["",false]

**Comment by charsbar** [comment]
JSON modules do not use a false value as a boolean. You always need to convert it to a special form. JSON modules now use JSON::PP::Boolean objects (or their equivalents) to express booleans more clearly. So please use them to express booleans. If you don't want to convert by yourself, you might want to use JSON::Types, which provides a set of simple wrappers.
