### ISSUE TITLE
Add a method to create a JSON boolean from a perl scalar

### ISSUE THREAD

**Issue by davidcantrelluk2** [makamaka/JSON#40]
We quite often find ourselves writing something like this:

`... $some_boolean ? JSON->true : JSON->false`

It would be nice if we could instead write:

`JSON->boolean($some_boolean)`

**Comment by moritz** [comment]
Any reason this issue is still open? The linked pull request has been merged, and a release has been cut.

**Comment by charsbar** [comment]
@moritz Thanks for the heads-up!
