### ISSUE TITLE
Please allow relaxed-json as defined here http://www.relaxedjson.org/

### ISSUE THREAD

**Issue by Skeeve** [makamaka/JSON#44]
Reason behind this request: I'm using [VSCodium](https://vscodium.com/) which already has built-in support for [Relaxed Json](http://www.relaxedjson.org/).

Issue is that the current variant of relaxed you support is not supported by VSCodium. So I either have to stick with standard JSON to get Syntax Highlighting or your relaxed variant and have JSON files with lots of highlighted errors.

**Comment by charsbar** [comment]
Thanks but I assume you're looking at a wrong place: https://metacpan.org/pod/JSON::Relaxed

**Comment by Skeeve** [comment]
Thanks for pointing me to that.

I'm wondering about this: I was looking at the source and found `sub white` which already seems to support `//` and `/* */`.

**Comment by Skeeve** [comment]
Got it!

`export PERL_JSON_BACKEND=JSON::PP`
